version: '2'
services:
  mysql_db:
    image: mysql:5.7
    command: 'mysqld --sql-mode=""'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tango_db
      MYSQL_USER: tango
      MYSQL_PASSWORD: tango
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d:ro
      - ./.data/mysql:/var/lib/mysql
  tango_databaseds:
    image: mliszcz/tango-cs:xenial
    environment:
      TANGO_HOST: 127.0.0.1:10000
      MYSQL_HOST: mysql_db
      MYSQL_DATABASE: tango_db
      MYSQL_USER: tango
      MYSQL_PASSWORD: tango
    depends_on:
      - mysql_db
    links:
      - mysql_db:mysql_db
