version: '2'
services:

  mariadb :
    image: mariadb:latest
    hostname: mariadb.workspace
    command: mysqld --sql-mode=""
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tango_db
      MYSQL_USER: tango
      MYSQL_PASSWORD: tango
    volumes:
      - ./.config/initdb:/docker-entrypoint-initdb.d:ro
      #- ./.data/mysql:/var/lib/mysql

  databaseds:
    image: tangocs/tango-cs:9
    hostname: databaseds.workspace
    command: >-
      /bin/sh -c 'wait-for-it.sh $${MYSQL_HOST} --timeout=30 --strict --
      supervisord -c /etc/supervisor/init.d/supervisord.databaseds.conf'
    environment:
      ORB_PORT: '10000'
      TANGO_HOST: databaseds.workspace:10000
      MYSQL_HOST: mariadb.workspace:3306
      MYSQL_DATABASE: tango_db
      MYSQL_USER: tango
      MYSQL_PASSWORD: tango
    volumes:
      - ./.config/supervisord:/etc/supervisor/init.d:ro
    links:
      - mariadb:mariadb.workspace

  tangotest:
    image: synchrotronsolaris/centos-tango-dev:latest
    hostname: tangotest.workspace
    command: >-
      /bin/sh -c 'wait-for-it.sh $${TANGO_HOST} --timeout=30 --strict --
      supervisord -c /etc/supervisor/init.d/supervisord.tangotest.conf'
    environment:
      TANGO_HOST: databaseds.workspace:10000
    volumes:
      - ./.config/supervisord:/etc/supervisor/init.d:ro
    links:
      - databaseds:databaseds.workspace

  taurus:
    image: synchrotronsolaris/centos-taurus:latest
    hostname: taurus.workspace
    environment:
      TANGO_HOST: databaseds.workspace:10000
      USER_NAME: tango
      USER_PASSWORD: tango
      DISPLAY: 192.168.120.205:0
    volumes:
      - ./.config/supervisord:/etc/supervisor/init.d:ro
    links:
      - databaseds:databaseds.workspace
