#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
JARDIR=$DIR/../.config/tools

DEPS=(
  JTango-9.0.7.jar
  ATKCore-9.1.13.jar
  ATKWidget-9.1.13.jar
  atkpanel-5.4.jar
  Jive-6.9.jar
  Astor-6.7.0.jar
)

CLASSPATH=("${DEPS[@]/#/$JARDIR/}")

java -cp $(IFS=:; echo "${CLASSPATH[*]}") admin.astor.Astor "$@"
